name: extendable_aiot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  http: ^1.3.0
  app_chiseletor: ^1.1.0+2
  provider: ^6.1.4
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  image_picker: ^1.0.7
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
