// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv6ZrwR6GSwj8j2o991W3w1Ln0meFrZb0',
    appId: '1:10965259978:web:db667568926f352ac50633',
    messagingSenderId: '10965259978',
    projectId: 'extendableaiot',
    authDomain: 'extendableaiot.firebaseapp.com',
    storageBucket: 'extendableaiot.firebasestorage.app',
    measurementId: 'G-ELXR98TKTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZKNdEIHlWUaWIG1rX41YZPEtiQuFplM',
    appId: '1:10965259978:android:00b82f9a141b9bdfc50633',
    messagingSenderId: '10965259978',
    projectId: 'extendableaiot',
    storageBucket: 'extendableaiot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvskP73Vo8rAG64xCd5IToZwzlxFXHGS0',
    appId: '1:10965259978:ios:da1e48384e25c6e6c50633',
    messagingSenderId: '10965259978',
    projectId: 'extendableaiot',
    storageBucket: 'extendableaiot.firebasestorage.app',
    iosBundleId: 'com.example.extendableAiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvskP73Vo8rAG64xCd5IToZwzlxFXHGS0',
    appId: '1:10965259978:ios:da1e48384e25c6e6c50633',
    messagingSenderId: '10965259978',
    projectId: 'extendableaiot',
    storageBucket: 'extendableaiot.firebasestorage.app',
    iosBundleId: 'com.example.extendableAiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv6ZrwR6GSwj8j2o991W3w1Ln0meFrZb0',
    appId: '1:10965259978:web:59b074263552d3e6c50633',
    messagingSenderId: '10965259978',
    projectId: 'extendableaiot',
    authDomain: 'extendableaiot.firebaseapp.com',
    storageBucket: 'extendableaiot.firebasestorage.app',
    measurementId: 'G-3R4SGS6NBE',
  );
}
